multiverse:
  length_unit: m
  angle_unit: rad
  force_unit: N
  time_unit: s
  handedness: rhs
  root_frame_id: map

  services:
    query_data:
      port: 7400

  publishers:
    tf:
      port: 7300
      rate: 60
    # visualization_marker_array:
    #   port: 7301
    #   rate: 60
