joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 60

head_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - head_pan_joint
    - head_tilt_joint

right_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - r_shoulder_pan_joint
    - r_shoulder_lift_joint
    - r_upper_arm_roll_joint
    - r_elbow_flex_joint
    - r_forearm_roll_joint
    - r_wrist_flex_joint
    - r_wrist_roll_joint

left_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - l_shoulder_pan_joint
    - l_shoulder_lift_joint
    - l_upper_arm_roll_joint
    - l_elbow_flex_joint
    - l_forearm_roll_joint
    - l_wrist_flex_joint
    - l_wrist_roll_joint

torso_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - torso_lift_joint